set editor nvim

# Show hidden files (dotfiles)
set show_hidden true

# Previews
set preview_files true
set preview_directories true
set use_preview_script true
set preview_script ~/.config/ranger/scope.sh
set preview_images false

# UI
set draw_borders both
set dirname_in_tabs true
set status_bar_on_top false
set mouse_enabled true

# Behaviour
set confirm_on_delete multiple
set save_console_history true
set scroll_offset 5
set autosave_bookmarks true

# Sorting
set sort natural
set sort_directories_first true
set sort_case_insensitive true
